# Project Identification
sonar.projectKey=wanderlust
sonar.projectName=wanderlust
sonar.projectVersion=1.0

# Source directories
sonar.sources=frontend,backend

# Encoding
sonar.sourceEncoding=UTF-8

# Exclude unnecessary files from analysis
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/*.test.js,**/*.spec.js,**/coverage/**